---
apiVersion: v1 # Select the type of API version and type of service/object
kind: Service
metadata:
  name: nginx-svc
  namespace: default

spec: 
  ports:
  - nodePort: 30001 #range is 30000-32768
    port: 80

    targetPort: 80

  selector:
    app: nginx # this label connects this service to deployment

  type: NodePort # also use LoadBalancer - for local use cluster IP


