---
apiVersion: v1 # Select the type of API version and type of service/object
kind: Service
metadata:
  name: app-svc
  namespace: default

spec: 
  ports:
  - nodePort: 30002 #range is 30000-32768
    port: 3000

    targetPort: 3000

  selector:
    app: node-app # this label connects this service to deployment

  type: NodePort # also use LoadBalancer - for local use cluster IP